# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_name', models.CharField(default=None, max_length=32, null=True)),
                ('runner_id', models.IntegerField(default=0)),
                ('runner_score', models.IntegerField(default=0)),
                ('corp_name', models.CharField(default=None, max_length=32, null=True)),
                ('corp_id', models.IntegerField(default=0)),
                ('corp_score', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=True)),
                ('win_type', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(verbose_name='date played')),
                ('exact_match', models.IntegerField(default=1)),
                ('runner_credits', models.IntegerField(default=None, null=True)),
                ('corp_credits', models.IntegerField(default=None, null=True)),
                ('runner_draws', models.IntegerField(default=None, null=True)),
                ('corp_draws', models.IntegerField(default=None, null=True)),
                ('runner_installs', models.IntegerField(default=None, null=True)),
                ('corp_installs', models.IntegerField(default=None, null=True)),
                ('runner_mulligan', models.NullBooleanField(default=None)),
                ('corp_mulligan', models.NullBooleanField(default=None)),
                ('runs', models.IntegerField(default=None, null=True)),
                ('turns', models.IntegerField(default=None, null=True)),
                ('deck_name', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('faction_code', models.CharField(max_length=32)),
                ('side_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='JintekiUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jinteki_username', models.CharField(max_length=32)),
                ('site_username', models.CharField(max_length=32)),
            ],
        ),
    ]
