# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='exact_match',
        ),
        migrations.AddField(
            model_name='game',
            name='game_hash',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
